# Zako source code ©2022 Noobly Walker, ©2022 OmniCoreStudios
from random import randrange
from util.cmdutil import cmdutil
text = cmdutil()

def rectColor(color):
    if set(color) <= set("0123456789"): #Stringified color integer
        return int(color)
    if set(color) <= set("0123456789,"): #Stringified RGB decimal
        color = color.split(",")
        for i in range(len(color)):
            color[i] = int(color[i])
    elif set(color) <= set("0123456789ABCDEFabcdefx,"): #Stringified RGB hex
        color = color.split(",")
        for i in range(len(color)):
            color[i] = int(color[i], 16)
    else: #Might be a color name
        color = color.lower()
        if color == "red": color = (255,0,0)
        if color in ["vermillion", "redorange"]: color = (255,64,0)
        if color == "orange": color = (255,128,0)
        if color in ["amber", "yelloworange"]: color = (255,192,0)
        if color == "yellow": color = (255,255,0)
        if color in ["chartreuse", "yellowgreen"]: color = (128,255,0)
        if color == "green": color = (0,255,0)
        if color == "mint": color = (0,255,128)
        if color in ["cyan", "bluegreen"]: color = (0,255,255)
        if color in ["cornflower", "cerulean"]: color = (0,128,255)
        if color == "blue": color = (0,0,255)
        if color in ["indigo", "bluepurple", "blueviolet"]: color = (64,0,255)
        if color in ["purple", "violet"]: color = (128,0,255)
        if color in ["magenta", "redpurple", "redviolet"]: color = (255,0,255)
        if color in ["darkred", "maroon"]: color = (128,0,0)
        if color in ["darkvermillion", "darkredorange", "brick", "copper"]: color = (128,32,0)
        if color in ["darkorange", "brown"]: color = (128,64,0)
        if color in ["darkamber", "brass", "darkyelloworange"]: color = (128,96,0)
        if color in ["darkyellow", "gold"]: color = (128,128,0)
        if color in ["darkchartreuse", "swamp", "darkyellowgreen"]: color = (64,128,0)
        if color in ["darkgreen", "forest"]: color = (0,128,0)
        if color == "darkmint": color = (0,128,64)
        if color in ["darkcyan", "teal", "darkbluegreen"]: color = (0,128,128)
        if color in ["darkcornflower", "darkcerulean"]: color = (0,64,128)
        if color in ["darkblue", "navy"]: color = (0,0,128)
        if color in ["darkindigo", "midnight", "darkbluepurple", "darkblueviolet"]: color = (32,0,128)
        if color in ["plum", "darkpurple", "darkviolet"]: color = (64,0,128)
        if color in ["darkmagenta", "eggplant", "darkredpurple", "darkredviolet"]: color = (128,0,128)
        if color in ["lightred", "pink"]: color = (255,128,128)
        if color in ["lightvermillion", "peach", "lightredorange"]: color = (255,160,128)
        if color == "lightorange": color = (255,192,128)
        if color in ["lightamber", "lightyelloworange", "electrum"]: color = (255,224,128)
        if color in ["lightyellow", "lemon"]: color = (255,255,128)
        if color in ["lightchartreuse", "avocado", "lightyellowgreen"]: color = (192,255,128)
        if color in ["lightgreen", "lime"]: color = (128,255,128)
        if color == "lightmint": color = (128,255,192)
        if color in ["lightcyan", "sky", "lightbluegreen"]: color = (128,255,255)
        if color in ["lightcornflower", "lightcerulean"]: color = (128,192,255)
        if color in ["lightblue", "slate"]: color = (128,128,255)
        if color in ["lightindigo", "lightbluepurple", "lightblueviolet"]: color = (160,128,255)
        if color in ["lightpurple", "lavender", "lightviolet"]: color = (192,128,255)
        if color in ["lightmagenta", "rose", "lightredpurple", "lightredviolet"]: color = (255,128,255)
        if color == "black": color = (0,0,0)
        if color in ["darkgray", "darkgrey"]: color = (64,64,64)
        if color in ["gray", "grey"]: color = (128,128,128)
        if color in ["lightgray", "lightgrey", "silver"]: color = (192,192,192)
        if color in ["white", "lightmode"]: color = (255,255,255)
        if color == "darkblurple": color = (78,93,148)
        if color == "blurple": color = (114,137,218)
        if color == "lightblurple": color = (150,181,255)
        if color == "darklightmode": color = (153,170,181)
        if color in ["darkmode", "invisible"]: color = (44,47,51)
        if color == "darkdarkmode": color = (35,39,42)
        if color == "random": color = (randrange(256),randrange(256),randrange(256))
    return color[0]*256*256+color[1]*256+color[2]
